"""Deterministic scalar corpora and diagnostic harness materialisation."""
import json
from pathlib import Path

INTEGERS = {"int", "long", "short", "signed", "signed int", "long long", "unsigned", "unsigned int",
            "unsigned long", "unsigned short", "unsigned long long", "char", "signed char", "unsigned char",
            "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "byte",
            "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32", "u64", "u128", "usize"}
FLOATS = {"float", "double", "f32", "f64", "float32", "float64", "number"}
STRINGS = {"str", "string", "String", "java.lang.String"}
BOOLS = {"bool", "boolean", "_Bool"}
VOIDS = {"void", "()", "None", "NoneType"}


def scalar_type(name):
    return name.replace("const ", "").strip()


def values(name, language):
    name = scalar_type(name)
    if name in BOOLS:
        return [False, True]
    if name in INTEGERS:
        return [0, 1, 2] if name.startswith(("u", "unsigned")) or name in ("byte", "char") else [0, 1, -1]
    if name in FLOATS:
        return [0.0, 1.0, -1.0]
    if name in STRINGS and language not in ("c", "cpp", "rust"):
        return ["", "a", "edge\nvalue"]
    if name in ("dynamic", "unknown") and language in ("python", "javascript", "typescript"):
        return [0, 1, -1, "", True, None]
    return None


def corpus(entry, count):
    pools = [values(t, entry["language"]) for t in entry["parameters"]]
    if any(pool is None for pool in pools):
        raise ValueError("argument type requires a concrete fixture")
    if not pools:
        return [[]]
    # Bounded diagonal plus shifted columns: deterministic, not exhaustive Cartesian coverage.
    return [[pool[(index + column) % len(pool)] for column, pool in enumerate(pools)] for index in range(count)]


def literal(value, type_, language):
    if language == "rust":
        if isinstance(value, bool):
            return str(value).lower()
        return str(value) + (".0" if type_ in ("f32", "f64") and type(value) is int else "") + type_
    if language == "go":
        return type_ + "(" + json.dumps(value) + ")"
    if language == "java" and type_ in ("byte", "short", "char", "long", "float"):
        return "(" + type_ + ")" + str(value).lower()
    if language == "c" and type(value) is bool:
        return "1" if value else "0"
    return json.dumps(value)


def global_gaps(entry):
    if entry["language"] in ("python", "javascript", "typescript"):
        return [g["name"] for g in entry["globals"] if g["name"].startswith("<")]
    scalar = INTEGERS | FLOATS | BOOLS
    if entry["language"] in ("go", "java"):
        scalar |= STRINGS
    return [g["name"] for g in entry["globals"]
            if scalar_type(g["type"]) not in scalar or g.get("private") or g.get("inaccessible")]


def python_driver(entry, args):
    globals_ = [g["name"] for g in entry["globals"]]
    return f'''# Generated by oteleq. Boilerplate is MIT licensed.
import importlib.util, json, os, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from _oteleq_observe import graph, MISSING
target = Path({entry['path']!r})
sys.path.insert(0, str(target.parent))
spec = importlib.util.spec_from_file_location("_oteleq_target", target)
module = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = module
spec.loader.exec_module(module)
arguments = {args!r}
def roots():
    return {{**{{"global:" + name: vars(module).get(name, MISSING) for name in {globals_!r}}}, "arguments": arguments}}
before = graph(roots())
try:
    result = getattr(module, {entry['name']!r})(*arguments)
except Exception as error:
    outcome = {{"kind": "error", "value": graph({{"error": error, **roots()}})}}
else:
    outcome = {{"kind": "return", "value": graph({{"result": result, **roots()}})}}
after = graph(roots())
Path(os.environ["OTELEQ_OBSERVATION"]).write_text(json.dumps({{"before": before, "outcome": outcome, "after": after}}, sort_keys=True))
'''


JS_OBSERVER = '''
const __oteleqIsProxy=(await import('node:util')).types.isProxy;
function __oteleqGraph(roots) {
  const seen = new Map(), nodes = [];
  function value(v, depth=0) {
    if(depth>32 || nodes.length>=512) throw new Error('observation graph limit');
    if(v===null) return {type:'null'};
    if(typeof v==='number') { const b=Buffer.alloc(8); b.writeDoubleBE(v); return {type:'float64',bits:b.toString('hex')}; }
    if(['boolean','string','undefined','bigint'].includes(typeof v)) return {type:typeof v,value:typeof v==='bigint'?v.toString():v};
    if(typeof v!=='object') throw new Error('opaque value: '+typeof v);
    if(__oteleqIsProxy(v)) throw new Error('proxy state requires a fixture');
    if(seen.has(v)) return {ref:seen.get(v)};
    const id=nodes.length; seen.set(v,id);
    const prototype=Object.getPrototypeOf(v);
    const errorPrototypes=[Error.prototype,TypeError.prototype,RangeError.prototype,SyntaxError.prototype,ReferenceError.prototype,URIError.prototype,EvalError.prototype,AggregateError.prototype];
    const isError=errorPrototypes.includes(prototype);
    if(![Object.prototype,Array.prototype,null].includes(prototype) && !isError) throw new Error('opaque object prototype');
    const n={type:isError?prototype.name:Array.isArray(v)?'array':'object',fields:[]}; nodes.push(n);
    for(const key of Reflect.ownKeys(v)) {
      if(isError && key==='stack') continue;
      if(typeof key!=='string') throw new Error('symbol state requires a fixture');
      const d=Object.getOwnPropertyDescriptor(v,key);
      if(!Object.hasOwn(d,'value')) throw new Error('accessor state requires a fixture');
      n.fields.push([key,value(d.value,depth+1),d.writable,d.enumerable,d.configurable]);
    }
    return {ref:id};
  }
  return {roots:Object.fromEntries(Object.keys(roots).sort().map(k=>[k,value(roots[k])])),nodes};
}
'''


def js_driver(entry, args, source):
    roots = "".join(json.dumps("global:" + g["name"]) + ":" + g["name"] + "," for g in entry["globals"])
    call = entry["name"] + "(...__oteleqArguments)"
    if entry.get("async"):
        call = "await " + call
    # Appended helpers are outside the exact function selection. The delta is recorded as diagnostic.
    return source + JS_OBSERVER + f'''
const __oteleqArguments={json.dumps(args)};
const __oteleqRoots=()=>({{{roots}arguments:__oteleqArguments}});
const __oteleqBefore=__oteleqGraph(__oteleqRoots());
let __oteleqOutcome, __oteleqResult, __oteleqFailed=false;
try {{ __oteleqResult={call}; }}
catch(error) {{ __oteleqFailed=true; __oteleqOutcome={{kind:'error',value:__oteleqGraph({{error,...__oteleqRoots()}})}}; }}
if(!__oteleqFailed) __oteleqOutcome={{kind:'return',value:__oteleqGraph({{result:__oteleqResult,...__oteleqRoots()}})}};
const __oteleqAfter=__oteleqGraph(__oteleqRoots());
const __oteleqFs=await import('node:fs');
__oteleqFs.writeFileSync(process.env.OTELEQ_OBSERVATION,JSON.stringify({{before:__oteleqBefore,outcome:__oteleqOutcome,after:__oteleqAfter}}));
'''


def native_driver(entry, args):
    parameters = ", ".join(literal(v, t, entry["language"]) for v, t in zip(args, entry["parameters"]))
    output = scalar_type(entry["output"])
    call = entry["name"] + "(" + parameters + ")"
    returned = call + "; fputs(\"return:void\\n\", out);" if output == "void" else output + " result=" + call + '; __oteleq_bytes(out,"return:' + output + '",&result,sizeof(result));'
    state = "\n".join('__oteleq_bytes(out,' + json.dumps(g["name"] + ":" + g["type"]) + ',&' + g["name"] + ',sizeof(' + g["name"] + '));' for g in entry["globals"])
    invocation = returned
    if entry["language"] == "cpp":
        invocation = 'try {' + returned + '} catch(const std::exception& e){fprintf(out,"error:%s:%s\\n",typeid(e).name(),e.what());} catch(...){fclose(out);return 91;}'
    headers = '#include <exception>\n#include <typeinfo>\n' if entry["language"] == "cpp" else ''
    return headers + '''#include <stdio.h>
#include <stdlib.h>
#define main __oteleq_original_main
#include ''' + json.dumps(entry["path"]) + '''
#undef main
static void __oteleq_bytes(FILE* out,const char* label,const void* v,size_t n){
  const unsigned char* p=(const unsigned char*)v; fprintf(out,"%s:",label);
  for(size_t i=0;i<n;i++) fprintf(out,"%02x",p[i]); fputc('\\n',out);
}
int main(void){ FILE* out=fopen(getenv("OTELEQ_OBSERVATION"),"wb"); if(!out)return 90;
fputs("before\\n",out);
''' + state + '\n' + invocation + '\nfputs("after\\n",out);\n' + state + '\nreturn fclose(out)!=0;}\n'


def rename_main(source, entries, language):
    main = next((e for e in entries if e["name"] == "main"), None)
    if not main:
        return source
    if language == "go":
        offset = main["name_offset"]
    else:
        offset = sum(len(line.encode()) for line in source.splitlines(keepends=True)[:main["line"] - 1]) + main["column"]
    encoded = source.encode()
    if encoded[offset:offset + 4] != b"main":
        raise ValueError("entrypoint source range does not match AST")
    return (encoded[:offset] + b"__oteleq_original_main" + encoded[offset + 4:]).decode()


def rust_driver(entry, args, source):
    call = entry["name"] + "(" + ",".join(literal(v, t, "rust") for v, t in zip(args, entry["parameters"])) + ")"
    output = scalar_type(entry["output"])
    formatted = 'format!("{:x}",v.to_bits())' if output in ("f32", "f64") else 'format!("{:?}",v)'
    state_lines = []
    for global_ in entry["globals"]:
        floating = scalar_type(global_["type"]) in ("f32", "f64")
        expression = "unsafe {" + global_["name"] + "}"
        if floating:
            expression = "(" + expression + ").to_bits()"
        pattern = ":{:x}\n" if floating else ":{:?}\n"
        state_lines.append('s.push_str(&format!(' + json.dumps(global_["name"] + ':' + global_["type"] + pattern) + ',' + expression + '));')
    state = "\n".join(state_lines)
    return rename_main(source, entry["file_functions"], "rust") + f'''
fn main() {{
    let mut s=String::from("before\\n"); {state}
    match std::panic::catch_unwind(|| {call}) {{
      Ok(v)=>s.push_str(&format!("return:{output}:{{}}\\n",{formatted})),
      Err(payload)=>{{
        if let Some(v)=payload.downcast_ref::<String>() {{ s.push_str(&format!("error:string:{{:?}}\\n",v)); }}
        else if let Some(v)=payload.downcast_ref::<&str>() {{ s.push_str(&format!("error:str:{{:?}}\\n",v)); }}
        else {{ std::process::exit(91); }}
      }},
    }}
    s.push_str("after\\n"); {state}
    std::fs::write(std::env::var("OTELEQ_OBSERVATION").unwrap(),s).unwrap();
}}
'''


def go_driver(entry, args, source):
    source = rename_main(source, entry["file_functions"], "go")
    position = entry["package_end"]
    imports = '\nimport (oteleqfmt "fmt"; oteleqos "os"; oteleqmath "math")\n'
    raw = source.encode()
    source = (raw[:position] + imports.encode() + raw[position:]).decode()
    call = entry["name"] + "(" + ",".join(literal(v, t, "go") for v, t in zip(args, entry["parameters"])) + ")"
    invoked = call + ';s+="return:void\\n"' if entry["output"] == "void" else 's+="return:"+__oteleqValue(' + call + ')+"\\n"'
    state = "\n".join('s+=' + json.dumps(g["name"] + ':') + '+__oteleqValue(' + g["name"] + ')+"\\n"' for g in entry["globals"])
    return source + f'''
func __oteleqValue(v any) string {{
 switch x:=v.(type) {{case float32: return oteleqfmt.Sprintf("float32:%x",oteleqmath.Float32bits(x));case float64:return oteleqfmt.Sprintf("float64:%x",oteleqmath.Float64bits(x))}}
 switch v.(type) {{case nil,bool,string,int,int8,int16,int32,int64,uint,uint8,uint16,uint32,uint64:default:panic("opaque observation requires a fixture")}}
 return oteleqfmt.Sprintf("%T:%#v",v,v)
}}
func main(){{
 s:="before\\n"; {state}
 func(){{defer func(){{if p:=recover();p!=nil{{s+="error:"+__oteleqValue(p)+"\\n"}}}}();{invoked}}}()
 s+="after\\n"; {state}
 if err:=oteleqos.WriteFile(oteleqos.Getenv("OTELEQ_OBSERVATION"),[]byte(s),0600);err!=nil{{panic(err)}}
}}
'''


def java_driver(entry, args):
    package = "package " + entry["package"] + ";\n" if entry["package"] else ""
    call = entry["name"] + "(" + ",".join(literal(v, t, "java") for v, t in zip(args, entry["parameters"])) + ")"
    invoked = call + ';s.append("return:void\\n");' if entry["output"] == "void" else 's.append("return:").append(value(' + call + ')).append("\\n");'
    state = "\n".join('s.append(' + json.dumps(g["name"] + ':') + ').append(value(' + g["name"] + ')).append("\\n");' for g in entry["globals"])
    return package + '''class OteleqDriver {
static String value(Object v){
 if(v==null)return "null";
 if(v instanceof Double x)return "double:"+Long.toHexString(Double.doubleToRawLongBits(x));
 if(v instanceof Float x)return "float:"+Integer.toHexString(Float.floatToRawIntBits(x));
 return v.getClass().getName()+":"+java.util.Base64.getEncoder().encodeToString(v.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));
}
public static void main(String[] args) throws Exception {
StringBuilder s=new StringBuilder("before\\n");
''' + state + '\ntry{' + invoked + '}catch(Exception e){s.append("error:").append(e.getClass().getName()).append(":").append(value(e.getMessage())).append("\\n");}\ns.append("after\\n");\n' + state + '\njava.nio.file.Files.writeString(java.nio.file.Path.of(System.getenv("OTELEQ_OBSERVATION")),s.toString());\n}}\n'


def materialise(project, entry, args):
    source = project / entry["path"]
    original = source.read_text()
    generated = project / "_oteleq_generated"
    generated.mkdir(exist_ok=True)
    language = entry["language"]
    if language == "python":
        driver = generated / "driver.py"
        driver.write_text(python_driver(entry, args))
        (generated / "_oteleq_observe.py").write_bytes(Path(__file__).with_name("observe.py").read_bytes())
    elif language in ("c", "cpp"):
        driver = project / ("_oteleq_driver.c" if language == "c" else "_oteleq_driver.cpp")
        driver.write_text(native_driver(entry, args))
    elif language == "java":
        driver = source.parent / "OteleqDriver.java"
        if driver.exists():
            raise ValueError("generated Java driver would overwrite an application file")
        driver.write_text(java_driver(entry, args))
    else:
        driver = source
        emit = {"javascript": js_driver, "typescript": js_driver, "rust": rust_driver, "go": go_driver}[language]
        driver.write_text(emit(entry, args, original))
    return driver
